# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howmany_voted', models.IntegerField(default=0, verbose_name='Number of photos that is voted by the contender')),
                ('total_points_given', models.IntegerField(default=0, verbose_name='Number of points that is distributed by the contender')),
                ('howmany_photos_owned', models.IntegerField(default=1, verbose_name='Photos that is sent to pool by the contender')),
                ('final_ranking', models.IntegerField(default=1, verbose_name='Final ranking')),
                ('prize_earned', models.TextField(blank=True)),
                ('achievement_earned', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Contest id')),
                ('contest_name', models.CharField(max_length=50, unique=True, verbose_name='Contest Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('tag', models.CharField(max_length=30, verbose_name='Contest Tag')),
                ('min_must_votes', models.IntegerField(default=10, verbose_name='Minimum number of votes a contender must provide')),
                ('min_avgrate_given', models.FloatField(default=4.0, verbose_name='Min average of given points a contender must provide')),
                ('max_photos_per_user', models.IntegerField(default=10, verbose_name='Max photos per user')),
                ('min_votes_must_gotten', models.IntegerField(default=10, verbose_name='Minimum number of votes must be gotten')),
                ('prize_distributions', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contender',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Contest id'),
        ),
        migrations.AddField(
            model_name='contender',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Username of contender'),
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together=set([('username', 'contest')]),
        ),
    ]
