# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20171221_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contender',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contender',
            name='username',
        ),
        migrations.DeleteModel(
            name='Contender',
        ),
    ]
