# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20171221_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='max_photos_per_user',
        ),
        migrations.AddField(
            model_name='contest',
            name='max_photos_per_Preuser',
            field=models.IntegerField(default=20, verbose_name='Max photos per Premium user'),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_photos_per_Reguser',
            field=models.IntegerField(default=5, verbose_name='Max photos per free user'),
        ),
    ]
