# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0004_auto_20171222_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howmany_voted', models.IntegerField(default=0, verbose_name='Number of photos that is voted by the contender')),
                ('total_points_given', models.IntegerField(default=0, verbose_name='Number of points that is distributed by the contender')),
                ('howmany_photos_owned', models.IntegerField(default=1, verbose_name='Photos that is sent to pool by the contender')),
                ('final_ranking', models.IntegerField(default=1, verbose_name='Final ranking')),
                ('prize_earned', models.TextField(blank=True)),
                ('achievement_earned', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='min_avgrate_given',
            new_name='min_total_points_given',
        ),
        migrations.AddField(
            model_name='contender',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Contest id'),
        ),
        migrations.AddField(
            model_name='contender',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterUniqueTogether(
            name='contender',
            unique_together=set([('user', 'contest')]),
        ),
    ]
