# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20171222_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='howmany_photos_owned',
            field=models.IntegerField(default=0, verbose_name='Photos that is sent to pool by the contender'),
        ),
    ]
