# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20171222_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
