# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20171222_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='min_votes_must_gotten',
        ),
    ]
