# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20171224_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='howmany_photos_owned',
            field=models.IntegerField(default=0, verbose_name='Photos that is sent to pool by the contender'),
        ),
        migrations.AlterField(
            model_name='contender',
            name='howmany_voted',
            field=models.IntegerField(default=0, verbose_name='Number of photos that is voted by the contender'),
        ),
    ]
