# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedPhotos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Report id')),
                ('photoId', models.IntegerField(verbose_name='Reported photo id')),
                ('howmany_reports', models.IntegerField(default=0, verbose_name='How many time reported?')),
                ('isOpen', models.BooleanField(default=True, verbose_name='Is the report is open?')),
                ('isHandled', models.BooleanField(default=False, verbose_name='Have any admins took a look at it?')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Is the reported photo deleted?')),
            ],
        ),
    ]
