# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedphotos',
            old_name='photoId',
            new_name='photoid',
        ),
    ]
