# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('reportedPhotos', '0002_auto_20180118_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedphotos',
            name='photoid',
        ),
        migrations.AddField(
            model_name='reportedphotos',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
        ),
    ]
