# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0003_auto_20180118_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedphotos',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
        ),
    ]
