# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0004_auto_20180118_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedphotos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
