# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0005_auto_20180118_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedphotos',
            name='photo',
        ),
    ]
