# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_remove_photo_report'),
        ('reportedPhotos', '0006_remove_reportedphotos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedphotos',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
        ),
    ]
