# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0007_reportedphotos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedphotos',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
        ),
    ]
