# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Username')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='E-mail')),
                ('realname', models.CharField(max_length=50, verbose_name='Name Surname')),
                ('email_verified', models.BooleanField(default=False, verbose_name='E-mail verification')),
                ('achievements', models.TextField(blank=True)),
                ('aboutme', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium status')),
            ],
        ),
    ]
