# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20171221_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
                ('email_verified', models.BooleanField(default=False, verbose_name='E-mail verification')),
                ('achievements', models.TextField(blank=True)),
                ('aboutme', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
