# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0002_auto_20180118_1546'),
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reported_photos',
            field=models.ManyToManyField(to='reportedPhotos.ReportedPhotos'),
        ),
    ]
