# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_reported_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reported_photos',
            field=models.ManyToManyField(blank=True, to='reportedPhotos.ReportedPhotos'),
        ),
    ]
