# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180118_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reported_photos',
            field=models.ManyToManyField(to='reportedPhotos.ReportedPhotos'),
        ),
    ]
