# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 10:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0011_auto_20171224_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Photo id')),
                ('photoItself', models.ImageField(default='blog/static/manzara.jpg', upload_to='photopool/', verbose_name='Photo')),
                ('uploading_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Yüklenme Tarihi')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contest.Contest', verbose_name='Contest name')),
                ('ownername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Name of the owner of the photo')),
            ],
        ),
    ]
