# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportedPhotos', '0006_remove_reportedphotos_photo'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportedPhotos.ReportedPhotos'),
        ),
    ]
