# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportedPhotos.ReportedPhotos'),
        ),
    ]
