# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180119_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='report',
        ),
    ]
